# https://www.playframework.com/documentation/latest/Configuration
# conf/application.conf
play.modules.enabled += "db.DatabaseModule"
db.default {
  driver   = "com.mysql.cj.jdbc.Driver"
  url      = "jdbc:mysql://localhost:3306/student management?useSSL=false&serverTimezone=UTC"
  username = "root"
  password = "database123"
}
play.evolutions.db.default.autoApply = true
# Quill reads from this "ctx" block
ctx.dataSource.url          = ${db.default.url}
ctx.dataSource.user         = ${db.default.username}
ctx.dataSource.password     = ${db.default.password}
ctx.dataSource.driverClassName = "com.mysql.cj.jdbc.Driver"

# Play secret key (change this in production)
play.http.secret.key = "changeme-123456789-abcdefghijklmnop-this-is-a-long-secret-key"

#JWT Configuration
jwt{
  #secret= ${?JWT_SECRET }
  secret="2oUI&tT8#;0W+E(]|dipr/iPfUA)?dWq$yaD|ZfMX[/"
  issuer="student management"
}
# BCrypt Configuration

bcrypt {
  logRounds = 10
}